### ISSUE TITLE
libgnat-13.so module missing

### ISSUE THREAD

**Issue by 95lux** [ghdl/ghdl-yosys-plugin#195]
I am trying to load the module with `yosys -m ghdl -p 'ghdl'` but get

```
ERROR: Can't load module `./ghdl': libgnat-13.so: cannot open shared object file: No such file or directory
```

I am on arch, and when trying to install libgnat with ada-gcc package, it only installs the libgnat-14.so library object.
I also tried building yosys, ghdl-yosys-plugin and ghdl from Github source, to rule out the possibility of outdated, or misconfigured packages form the AUR.

Is the dependency of libgnat13 correct?

**Comment by Xiretza** [comment]
You built ghdl while GCC 13 was current. Now, GCC 14 is current. Rebuild ghdl.

**Comment by 95lux** [comment]
Thanks alot! I recompiled ghdl, and yosys plugin. Now i got a working installation again!
Sorry for opening an issue for it.
